on: 
 workflow_dispatch:
 push:
   branches:
   - main

 pull_request:
   branches:
   - main

jobs:
  test:
    name: Sample unit test
    runs-on: ubuntu-latest

    steps:
    - uses : actions/checkout@v2
    - name: checkout respository

    - name: run script hello
      run: echo "hello world!" 
      shell: bash

          
        
      
