name: First workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Hello World Test on Ubuntu
        run: echo "Hello World!"
        shell: bash

  build_windows:
    name: Build and Test on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Hello World Test on Windows
        run: echo "Hello World!"
        shell: bash
